apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
  name: {{ include "dynamic-configmap-propagator.clusterole.name" . }}
rules:
  - apiGroups: ["syncer.custom"]
    resources: ["configmapsyncers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["syncer.custom"]
    resources: ["configmapsyncers/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "update", "delete", "patch", "get", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "update", "delete", "patch", "get", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "update", "delete", "patch", "get", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create","patch", "get"]