apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dynamic-configmap-propagator.serviceaccount.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
